// Beanstalk Runtime System
//
// This module provides the runtime infrastructure for executing WASM generated by the Beanstalk compiler.
// It's designed to be pluggable and separate from the compiler itself, supporting multiple execution
// environments and IO backends.
pub mod host_io_functions {
    pub mod custom;
    pub mod io;
    pub mod js_bindings;
    pub mod native;
}
pub mod jit;
